version: 0.2

phases:
  build:
    commands:
      - echo "Building project"
      - mkdir -p output
      - if [ -d "source-directory" ]; then cp -r source-directory/* output/; else echo "Source directory not found"; fi

artifacts:
  files:
    - '**/*'
  base-directory: output